import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <main>
          <div className="flex flex-col gap-4 justify-center items-center p-10">
          <input
            className="focus:shadow-outline block appearance-none rounded-lg border border-gray-300 bg-white px-4 py-2 leading-normal focus:outline-none"
            type="email"
            placeholder="jane@example.com"
          />
          <h1 className="text-3xl font-bold underline">Hello, Next.js!</h1>
          </div>
        </main>
      </div>
    </>
  )
}
